name: Validate

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  validation:
    uses: SpencerRWood/workflows/.github/workflows/validate.yml@8d3acbcb4faeae1f059aa8faad71ce5de964bc1c
